# DSDL Data Science Environment: Docker Compose Configuation
# This notebooks deploys a "static" DSDL environment in docker with no dynamic control needed from the DSDL app
# It contains a DSDL dev container, as well as optional Milvus supporting services
version: '1.0'

# ------------------------------------------------------------------------------------------------------------------------ #

# Define all services: Ollama, DSDL Dev

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/ollama:/root/.ollama
    
  # ------------------------------------------------------------------------------------------------------------------------ #
  # DSDL Dev Container - not optional, required for DSDL operation
  dsdl-dev:
    extends:
      file: dsdl-base.yml
      service: dsdl-base
    container_name: dsdl-dev
    image: phdrieger/mltk-container-golden-image-cpu:5.1.0
    ports:
     - 8888:8888 # Jupyter
     - 6000:6000
     - 4040:4040
     - 6006:6006 # Tensorboard
    environment:
     - MODE_DEV_PROD=DEV

# ------------------------------------------------------------------------------------------------------------------------ #
volumes:
  mltk-container-data:
  mltk-container-app:
  mltk-container-notebooks:

# ------------------------------------------------------------------------------------------------------------------------ #
networks:
  default:
    name: dsenv-network
